#!/usr/bin/env zsh

# stolen from ThePrimeagen https://github.com/ThePrimeagen/.dotfiles/blob/4a8d2a7fe12293db872f7b932dae339442de0b2f/install

# He writes:
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
