#!/usr/bin/env bash


# open-session <path>
# open-session ~/projects/ncko/cfsandbox-tf

session=$1
session_name=$(basename "$session" | tr . _)
in_tmux_session=$TMUX
tmux_running=$(pgrep tmux)

# if not (-z) in tmux session and tmux is not running
if [[ -z $in_tmux_session ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $session_name -c $session
	exit 0
fi

# if tmux does not (!) have a session with the name $session_name
if ! tmux has-session -t "$session_name" 2> /dev/null; then
	tmux new-session -s "$session_name" -c "$session" -d
fi

# if not (-z) in tmux session and tmux is running
if [[ -z $in_tmux_session ]]; then
	tmux attach-session -t $session_name
else
	tmux switch-client -t $session_name
fi
