#!/usr/bin/env bash

# Get an ubuntu ami

curl -s https://cloud-images.ubuntu.com/locator/ec2/releasesTable\?_\=1665631857959 \
    | json5 \
    | jq -cr '.aaData[] | join("\t")' \
    | awk -F '\t' '{print $1 "\t" $3 "\t" $4 "\t" $5 "\t" $7}' \
    | fzf \
    | awk -F '\t' '{print $5}' \
    | pup 'text{}' \
    | head -n 1

